"""Added User, FacebookAccount

Revision ID: 58533af39fd7
Revises: None
Create Date: 2013-02-04 19:44:58.018873

"""

# revision identifiers, used by Alembic.
revision = '58533af39fd7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(True), nullable=False),
    sa.Column('updated', sa.DateTime(True), nullable=False),
    sa.Column('nickname', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    )
    op.create_table('facebook_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(True), nullable=False),
    sa.Column('updated', sa.DateTime(True), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, index=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid'),
    sa.UniqueConstraint('user_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facebook_accounts')
    op.drop_table('users')
    ### end Alembic commands ###
